src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Last_Payment_Date__c</fullName>
        <description>The most recent payment date made by this contact across all projects</description>
        <label>Last Payment Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Total_Payments_Applied__c</fullName>
        <description>Total amount of payments applied for this contact</description>
        <label>Total Payments Applied</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <description>This object will be used to store payment information</description>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Payment Amount</description>
        <label>Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup Relationship To Contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <description>Payment date of the corresponding payment</description>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Master Detail relationship to Project to assign payments a project</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContactDataService.cls
/****************************************
* @classname: ContactDataService.cls
* @author: mhavrilla
* @abstract:  Dataservice class for the Contact object
*****************************************/

public class ContactDataService {


  /**
  * Returns all contacts with associated payments. 
  * @retun contacts;
  */
  public static List<Contact> getAllContactsWithPayments() {
    List<Contact> contacts = new List<Contact>();
    
    contacts = [select Id, Name, Total_Payments_Applied__c, Last_Payment_Date__c,
                  (
                    select Id, Name, Contact__c, Project__r.Name, Project__c, Amount__c, Payment_Date__c
                      from Payments__r 
                     where Project__c != null
                  )
                  from Contact
                ];

    return contacts;
  }
}